version: "3"
services:
  db:
    # container_name: typesctipt-nestjs-example-postgres
    image: postgres:14
    ports:
      - 54321:5432
    # volumes:
    #   - ./mock/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: example
      POSTGRES_PASSWORD: password