version: "3"
services:
  db:
    container_name: typesctipt-nestjs-example-postgres
    image: postgres:15
    ports:
      - 54321:5432
    # volumes:
    #   - ./mock/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: example
      POSTGRES_PASSWORD: password

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3001
  #   restart: always
  #   volumes:
  #     - .:/app/